POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "SujanThapa",
  "email": "sujanthapa4001@gmail.com",
  "password": "sujanthapa2005",
  "courseId": "e2090889-4398-4337-84d0-f41aff27d3db"
}


# GET http://localhost:3000/api/auth/greet
